[package]
name = "lunaro_plus"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
discord-sdk = "0.3.0"
screenshots = "0.4.3"
leptess = "0.13.2"
substring = "1.4.5"